///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelTests.CustomRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CaptureCellValue recording.
    /// </summary>
    [TestModule("c468567f-d0d9-4059-aa12-56c7aca3125d", ModuleType.Recording, 1)]
    public partial class CaptureCellValue : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ExcelTests.ExcelTestsRepository repository.
        /// </summary>
        public static global::ExcelTests.ExcelTestsRepository repo = global::ExcelTests.ExcelTestsRepository.Instance;

        static CaptureCellValue instance = new CaptureCellValue();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CaptureCellValue()
        {
            CapturedCellValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CaptureCellValue Instance
        {
            get { return instance; }
        }

#region Variables

        string _CapturedCellValue;

        /// <summary>
        /// Gets or sets the value of variable CapturedCellValue.
        /// </summary>
        [TestVariable("81c9c8b2-e12a-4f02-8c46-8d64a2b68fc6")]
        public string CapturedCellValue
        {
            get { return _CapturedCellValue; }
            set { _CapturedCellValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'Book1Excel.CellA6'.", repo.Book1Excel.CellA6Info, new RecordItemIndex(0));
            repo.Book1Excel.CellA6.Focus();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "Formula Cell Value", repo.Book1Excel.CellA6, false, new RecordItemIndex(1));
            
            // Assign Text value to local vareiable
            Report.Log(ReportLevel.Info, "Get Value", "Assign Text value to local vareiable\r\nGetting attribute 'Text' from item 'Book1Excel.CellA6' and assigning its value to variable 'CapturedCellValue'.", repo.Book1Excel.CellA6Info, new RecordItemIndex(2));
            CapturedCellValue = repo.Book1Excel.CellA6.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Captured Cell Value", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "User", CapturedCellValue, new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
