///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelTests.CustomRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ModifyCell recording.
    /// </summary>
    [TestModule("a7bc4995-33fa-42be-aaac-0fb1c3f710ec", ModuleType.Recording, 1)]
    public partial class ModifyCell : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ExcelTests.ExcelTestsRepository repository.
        /// </summary>
        public static global::ExcelTests.ExcelTestsRepository repo = global::ExcelTests.ExcelTestsRepository.Instance;

        static ModifyCell instance = new ModifyCell();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ModifyCell()
        {
            ModifiedCellValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ModifyCell Instance
        {
            get { return instance; }
        }

#region Variables

        string _ModifiedCellValue;

        /// <summary>
        /// Gets or sets the value of variable ModifiedCellValue.
        /// </summary>
        [TestVariable("c18fee75-9cba-4ae1-82a0-15924b1bca1d")]
        public string ModifiedCellValue
        {
            get { return _ModifiedCellValue; }
            set { _ModifiedCellValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Screenshot(ReportLevel.Info, "User", "Old Value", repo.Book1Excel.CellA1, false, new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.CellA1' at 54;10.", repo.Book1Excel.CellA1Info, new RecordItemIndex(1));
            repo.Book1Excel.CellA1.Click("54;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ModifiedCellValue' with focus on 'Book1Excel.CellA1'.", repo.Book1Excel.CellA1Info, new RecordItemIndex(2));
            repo.Book1Excel.CellA1.PressKeys(ModifiedCellValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab down}' with focus on 'Book1Excel.CellA1'.", repo.Book1Excel.CellA1Info, new RecordItemIndex(3));
            repo.Book1Excel.CellA1.PressKeys("{Tab down}");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "New Value", repo.Book1Excel.CellA1, false, new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
