///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateWorkbook recording.
    /// </summary>
    [TestModule("d1458472-36e9-4632-aa10-b28b621b9138", ModuleType.Recording, 1)]
    public partial class CreateWorkbook : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ExcelTestsRepository repository.
        /// </summary>
        public static ExcelTestsRepository repo = ExcelTestsRepository.Instance;

        static CreateWorkbook instance = new CreateWorkbook();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateWorkbook()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateWorkbook Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.SomeListItem' at 114;136.", repo.Book1Excel.SomeListItemInfo, new RecordItemIndex(0));
            repo.Book1Excel.SomeListItem.Click("114;136");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.FileTabButton' at 32;14.", repo.Book1Excel.FileTabButtonInfo, new RecordItemIndex(1));
            repo.Book1Excel.FileTabButton.Click("32;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.SaveAs' at 94;29.", repo.Book1Excel.SaveAsInfo, new RecordItemIndex(2));
            repo.Book1Excel.SaveAs.Click("94;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.Browse1' at 104;12.", repo.Book1Excel.Browse1Info, new RecordItemIndex(3));
            repo.Book1Excel.Browse1.Click("104;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ButtonSave' at 16;18.", repo.ButtonSaveInfo, new RecordItemIndex(4));
            repo.ButtonSave.Click("16;18");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
