///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Failed recording.
    /// </summary>
    [TestModule("103e23a1-1886-419b-914f-69daf2c15756", ModuleType.Recording, 1)]
    public partial class Failed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ExcelTestsRepository repository.
        /// </summary>
        public static ExcelTestsRepository repo = ExcelTestsRepository.Instance;

        static Failed instance = new Failed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Failed()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Failed Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Failure, "User", "Formula Cell returns an invalid value", new RecordItemIndex(0));
            
            Report.Screenshot(ReportLevel.Info, "User", "Cell Value", repo.Book1Excel.CellA6, false, new RecordItemIndex(1));
            
            Report.Screenshot(ReportLevel.Info, "User", "Formula Value", repo.Book1Excel.EXCEL1, false, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
