///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectWorkbook recording.
    /// </summary>
    [TestModule("e337fc52-855a-473a-9445-dee733c1f814", ModuleType.Recording, 1)]
    public partial class SelectWorkbook : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ExcelTestsRepository repository.
        /// </summary>
        public static ExcelTestsRepository repo = ExcelTestsRepository.Instance;

        static SelectWorkbook instance = new SelectWorkbook();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectWorkbook()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectWorkbook Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "Opening Workbook...", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.OpenOtherWorkbooks' at 123;8.", repo.Book1Excel.OpenOtherWorkbooksInfo, new RecordItemIndex(1));
            repo.Book1Excel.OpenOtherWorkbooks.Click("123;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.Browse' at 76;23.", repo.Book1Excel.BrowseInfo, new RecordItemIndex(2));
            repo.Book1Excel.Browse.Click("76;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.SystemItemNameDisplay' at 28;1.", repo.Book1Excel.SystemItemNameDisplayInfo, new RecordItemIndex(3));
            repo.Book1Excel.SystemItemNameDisplay.Click("28;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book1Excel.ButtonOpen1' at 33;14.", repo.Book1Excel.ButtonOpen1Info, new RecordItemIndex(4));
            repo.Book1Excel.ButtonOpen1.Click("33;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Workbook Opened.", new RecordItemIndex(5));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
